### ISSUE TITLE
2 minor issues in python_android.rst

### ISSUE THREAD

**Issue by yan12125** [vstinner/notes#1]
Thanks for compiling up this document! That's a nice material. Here are some minor issues:

* My build scripts https://github.com/yan12125/python3-android once supported android-19, while it's now targeting android-21 or newer after I bought a new phone with Lollipop (API 21).
* Here's a typo:

> Chih-Hsuan Ye aka yan12125

A missing "n" :)

**Comment by vstinner** [comment]
Oh, I beg you pardon for the name. It's a copy-paste mistake :-/

It's now fixed, thanks for the report.

**Comment by yan12125** [comment]
No problem :)
